// Copyright(c) 2024 rehans.

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "JitterMonitor.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "JitterMonitor VST3 (64Bit)"
#else
#define stringFileDescription "JitterMonitor VST3"
#endif
#define stringCompanyName "rhans\0"
#define stringLegalCopyright                                                   \
    "Copyright(c) 2024 rhans."
#define stringLegalTrademarks                                                  \
    "VST is a trademark of Steinberg Media Technologies GmbH"
